# -*- coding: utf-8 -*-
"""NN-PyTorch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K4R-Mf3e9NDcJj3Pyl9DACQcWrJyQpRx
"""

# Building an Neural Network using PyTorch

# Step 01: Import

import torch # core library
import torch.nn as nn # nn is neural layer tools as layer & model
import torch.optim as optim #optimizer (weights to update)

# Data Step 02:

X = torch.tensor([[0,0],[0,1],[1,0],[1,1]], dtype=torch.float32)
y = torch.tensor([[0],[1],[1],[0]], dtype=torch.float32)

# Step 03: Model (Neural Network)

# class Model(nn.Module): # create your own neural network class nn is base class for all models
  #def __init__(self):
    #super(Model, self).__init__() # super() is used to connect with pytorch system
    # self.fc1 = nn.Linear(2, 2)
    # self.fc2 = nn.Linear(2, 1)


# here the forward fucntion will remain same because we are doing forward propagation over here
# def forward(self, x):
   # ...
    #return x

# we will be having another actvation fucntion
# torch.relu(...)
# torch.softmax(...)

class Model(nn.Module):
    def __init__(self):   # constructor it run automaticaly when we create the model
        super(Model, self).__init__()   # __init__ runs first and then define neural networks
        self.fc1 = nn.Linear(2, 2)  # super is a keword that used to connect your class to pytorch base class
        self.fc2 = nn.Linear(2, 1)

    def forward(self, x):
        x = torch.sigmoid(self.fc1(x))
        x = torch.sigmoid(self.fc2(x))
        return x

model = Model()

# This structure remains same
# class Model(nn.Module):
    #def __init__(self):
        #super(Model, self).__init__()

    #def forward(self, x):
        #return x

# nn.Linear(in_features, out_features)
# nn.Linear(2,2) # takes two input and produces 2 output
# weight 2x2
# bias 1x2

# Step 03:- Forward Pass

# def forward(self,x):    # defines how data flows
  # x = torch.sigmoid(self.fc1(x))  # input -> hidden -> activation
  # x = torch.sigmoid(self.fc2(x))   # hidden -> output
  # return x    # final prediction

# Step 04: Loss Function

critterion = nn.BCELoss()

# Step 05 : optimizer

optimizer = optim.SGD(model.parameters(), lr=0.1)

# lr -> learning rate
# here the optimizer will get change

# Step 06: Training Loop



for epoch in range(10000):
    outputs = model(X)
    loss = criterion(outputs, y)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

print(model(X))

